/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author lucaszhang
 */
public class CreateJPanel extends javax.swing.JPanel {

    private Application application;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldObservationID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldTemperature = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldBloodPressure = new javax.swing.JTextField();
        addObservationbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CREATE A VITAL SIGN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 20, 20));
        add(fieldObservationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));

        jLabel3.setText("Temperature");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, -1));

        jLabel4.setText("Blood Pressure");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 20));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 130, -1));

        addObservationbtn.setText("ADD OBSERVATION");
        addObservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObservationbtnActionPerformed(evt);
            }
        });
        add(addObservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObservationbtnActionPerformed
        // TODO add your handling code here:
        VitalSignHistory history = this.application.getHistory();
        
        String id = fieldObservationID.getText();
        String temperature = fieldTemperature.getText();
        String bloodPressure = fieldBloodPressure.getText();
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(temperature), Double.valueOf(bloodPressure));
        
        JOptionPane.showMessageDialog(null, "Added observation");
    }//GEN-LAST:event_addObservationbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObservationbtn;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObservationID;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
