/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Application;

/**
 *
 * @author lucaszhang
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Application application;
    
    public MainJFrame() {
        initComponents();
        this.application = new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlJPanel = new javax.swing.JPanel();
        assignbtn = new javax.swing.JButton();
        createObservationbtn = new javax.swing.JButton();
        viewVitalbtn = new javax.swing.JButton();
        medCatalogbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignbtn.setText("ASSIGN MEDICINE");
        assignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(assignbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        createObservationbtn.setText("CREATE OBSERVATION");
        createObservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createObservationbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(createObservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        viewVitalbtn.setText("VIEW VITAL SIGN HISTORY");
        viewVitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(viewVitalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        medCatalogbtn.setText("MEDICINE CATALOG");
        medCatalogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medCatalogbtnActionPerformed(evt);
            }
        });
        ControlJPanel.add(medCatalogbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jSplitPane1.setLeftComponent(ControlJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createObservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObservationbtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateJPanel(this.application));
    }//GEN-LAST:event_createObservationbtnActionPerformed

    private void viewVitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalbtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewJPanel(this.application));
    }//GEN-LAST:event_viewVitalbtnActionPerformed

    private void medCatalogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medCatalogbtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CatalogJPanel(this.application));
    }//GEN-LAST:event_medCatalogbtnActionPerformed

    private void assignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignbtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new MedicineAssignJPanel(this.application));
    }//GEN-LAST:event_assignbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJPanel;
    private javax.swing.JButton assignbtn;
    private javax.swing.JButton createObservationbtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medCatalogbtn;
    private javax.swing.JButton viewVitalbtn;
    // End of variables declaration//GEN-END:variables
}
