/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author lucaszhang
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        viewOfficeEmail = new javax.swing.JTextField();
        viewPermanentZipCode = new javax.swing.JTextField();
        viewPersonalEmail = new javax.swing.JTextField();
        PersonalPhone1 = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JTextField();
        PersonalEmail1 = new javax.swing.JLabel();
        CurrentAddress1 = new javax.swing.JLabel();
        CurrentStreetName1 = new javax.swing.JLabel();
        viewCurrentStreetName = new javax.swing.JTextField();
        CurrentApartmentNumber1 = new javax.swing.JLabel();
        viewCurrentApartmentNumber = new javax.swing.JTextField();
        CurrentCity1 = new javax.swing.JLabel();
        viewCurrentCity = new javax.swing.JTextField();
        CurrentZipCode1 = new javax.swing.JLabel();
        viewNUID = new javax.swing.JTextField();
        viewCurrentZipCode = new javax.swing.JTextField();
        NUID1 = new javax.swing.JLabel();
        PermanentAddress1 = new javax.swing.JLabel();
        LastName1 = new javax.swing.JLabel();
        PermanentStreetName1 = new javax.swing.JLabel();
        CollegeName1 = new javax.swing.JLabel();
        viewPermanentStreetName = new javax.swing.JTextField();
        viewCollegeName = new javax.swing.JTextField();
        PermanentApartmentNumber1 = new javax.swing.JLabel();
        ContactInformation1 = new javax.swing.JLabel();
        OfficePhone1 = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JTextField();
        FirstName1 = new javax.swing.JLabel();
        viewLastName = new javax.swing.JTextField();
        viewPermanentApartmentNumber = new javax.swing.JTextField();
        PermanentCity1 = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JTextField();
        viewPermanentCity = new javax.swing.JTextField();
        OfficeEmail1 = new javax.swing.JLabel();
        PermanentZipCode1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fieldFirstName = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fieldLastName = new javax.swing.JTextField();
        fieldNUID = new javax.swing.JTextField();
        NUID = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        CollegeName = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        ContactInformation = new javax.swing.JLabel();
        OfficePhone = new javax.swing.JLabel();
        fieldOfficePhone = new javax.swing.JTextField();
        OfficeEmail = new javax.swing.JLabel();
        fieldOfficeEmail = new javax.swing.JTextField();
        fieldPersonalEmail = new javax.swing.JTextField();
        PersonalPhone = new javax.swing.JLabel();
        fieldPersonalPhone = new javax.swing.JTextField();
        PersonalEmail = new javax.swing.JLabel();
        CurrentAddress = new javax.swing.JLabel();
        CurrentStreetName = new javax.swing.JLabel();
        fieldCurrentStreetName = new javax.swing.JTextField();
        CurrentApartmentNumber = new javax.swing.JLabel();
        fieldCurrentApartmentNumber = new javax.swing.JTextField();
        CurrentCity = new javax.swing.JLabel();
        fieldCurrentCity = new javax.swing.JTextField();
        CurrentZipCode = new javax.swing.JLabel();
        fieldCurrentZipCode = new javax.swing.JTextField();
        PermanentAddress = new javax.swing.JLabel();
        PermanentStreetName = new javax.swing.JLabel();
        fieldPermanentStreetName = new javax.swing.JTextField();
        PermanentApartmentNumber = new javax.swing.JLabel();
        fieldPermanentApartmentNumber = new javax.swing.JTextField();
        PermanentCity = new javax.swing.JLabel();
        fieldPermanentCity = new javax.swing.JTextField();
        PermanentZipCode = new javax.swing.JLabel();
        fieldPermanentZipCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewOfficeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOfficeEmailActionPerformed(evt);
            }
        });
        jPanel1.add(viewOfficeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 299, 150, -1));

        viewPermanentZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPermanentZipCodeActionPerformed(evt);
            }
        });
        jPanel1.add(viewPermanentZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 472, 150, -1));

        viewPersonalEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonalEmailActionPerformed(evt);
            }
        });
        jPanel1.add(viewPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 299, 150, -1));

        PersonalPhone1.setText("Personal Phone");
        jPanel1.add(PersonalPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 272, -1, -1));

        viewPersonalPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonalPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(viewPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 267, 150, -1));

        PersonalEmail1.setText("Personal email");
        jPanel1.add(PersonalEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 304, -1, -1));

        CurrentAddress1.setText("Current Address");
        jPanel1.add(CurrentAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 337, -1, -1));

        CurrentStreetName1.setText("Street Name");
        jPanel1.add(CurrentStreetName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 381, -1, -1));

        viewCurrentStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCurrentStreetNameActionPerformed(evt);
            }
        });
        jPanel1.add(viewCurrentStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 376, 150, -1));

        CurrentApartmentNumber1.setText("Apt. No");
        jPanel1.add(CurrentApartmentNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 418, -1, -1));

        viewCurrentApartmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCurrentApartmentNumberActionPerformed(evt);
            }
        });
        jPanel1.add(viewCurrentApartmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 408, 150, -1));

        CurrentCity1.setText("City/State");
        jPanel1.add(CurrentCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 450, -1, -1));

        viewCurrentCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCurrentCityActionPerformed(evt);
            }
        });
        jPanel1.add(viewCurrentCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 440, 150, -1));

        CurrentZipCode1.setText("ZipCode");
        jPanel1.add(CurrentZipCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 482, -1, -1));
        jPanel1.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 93, 364, -1));

        viewCurrentZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCurrentZipCodeActionPerformed(evt);
            }
        });
        jPanel1.add(viewCurrentZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 472, 150, -1));

        NUID1.setText("NUID");
        jPanel1.add(NUID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 93, -1, 26));

        PermanentAddress1.setText("Permanent Address");
        jPanel1.add(PermanentAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 337, -1, -1));

        LastName1.setText("Last Name");
        jPanel1.add(LastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 169, -1, 26));

        PermanentStreetName1.setText("Street Name");
        jPanel1.add(PermanentStreetName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 381, -1, -1));

        CollegeName1.setText("College Name");
        jPanel1.add(CollegeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 201, -1, 26));

        viewPermanentStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPermanentStreetNameActionPerformed(evt);
            }
        });
        jPanel1.add(viewPermanentStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 376, 150, -1));

        viewCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCollegeNameActionPerformed(evt);
            }
        });
        jPanel1.add(viewCollegeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 201, 364, -1));

        PermanentApartmentNumber1.setText("Apt. No");
        jPanel1.add(PermanentApartmentNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 418, -1, -1));

        ContactInformation1.setText("Contact Information");
        jPanel1.add(ContactInformation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 239, -1, -1));

        OfficePhone1.setText("Office Phone");
        jPanel1.add(OfficePhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 267, -1, -1));
        jPanel1.add(viewFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 131, 364, -1));

        FirstName1.setText("First Name");
        jPanel1.add(FirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 131, -1, 26));

        viewLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 169, 364, -1));

        viewPermanentApartmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPermanentApartmentNumberActionPerformed(evt);
            }
        });
        jPanel1.add(viewPermanentApartmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 408, 150, -1));

        PermanentCity1.setText("City/State");
        jPanel1.add(PermanentCity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 450, -1, -1));

        viewOfficePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOfficePhoneActionPerformed(evt);
            }
        });
        jPanel1.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 267, 150, -1));

        viewPermanentCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPermanentCityActionPerformed(evt);
            }
        });
        jPanel1.add(viewPermanentCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 150, -1));

        OfficeEmail1.setText("Office email");
        jPanel1.add(OfficeEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 304, -1, -1));

        PermanentZipCode1.setText("ZipCode");
        jPanel1.add(PermanentZipCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 482, -1, -1));

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        FirstName.setText("First Name");

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        NUID.setText("NUID");

        LastName.setText("Last Name");

        CollegeName.setText("College Name");

        fieldCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCollegeNameActionPerformed(evt);
            }
        });

        ContactInformation.setText("Contact Information");

        OfficePhone.setText("Office Phone");

        fieldOfficePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfficePhoneActionPerformed(evt);
            }
        });

        OfficeEmail.setText("Office email");

        fieldOfficeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfficeEmailActionPerformed(evt);
            }
        });

        fieldPersonalEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonalEmailActionPerformed(evt);
            }
        });

        PersonalPhone.setText("Personal Phone");

        fieldPersonalPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPersonalPhoneActionPerformed(evt);
            }
        });

        PersonalEmail.setText("Personal email");

        CurrentAddress.setText("Current Address");

        CurrentStreetName.setText("Street Name");

        fieldCurrentStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentStreetNameActionPerformed(evt);
            }
        });

        CurrentApartmentNumber.setText("Apt. No");

        fieldCurrentApartmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentApartmentNumberActionPerformed(evt);
            }
        });

        CurrentCity.setText("City/State");

        fieldCurrentCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentCityActionPerformed(evt);
            }
        });

        CurrentZipCode.setText("ZipCode");

        fieldCurrentZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurrentZipCodeActionPerformed(evt);
            }
        });

        PermanentAddress.setText("Permanent Address");

        PermanentStreetName.setText("Street Name");

        fieldPermanentStreetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentStreetNameActionPerformed(evt);
            }
        });

        PermanentApartmentNumber.setText("Apt. No");

        fieldPermanentApartmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentApartmentNumberActionPerformed(evt);
            }
        });

        PermanentCity.setText("City/State");

        fieldPermanentCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentCityActionPerformed(evt);
            }
        });

        PermanentZipCode.setText("ZipCode");

        fieldPermanentZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentZipCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactInformation)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(CurrentStreetName)
                                                        .addComponent(CurrentApartmentNumber)
                                                        .addComponent(CurrentCity)
                                                        .addComponent(CurrentZipCode))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(fieldCurrentStreetName, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fieldCurrentApartmentNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fieldCurrentCity, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fieldCurrentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(CurrentAddress)
                                                    .addGap(148, 148, 148)))
                                            .addGap(12, 12, 12)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PermanentStreetName)
                                                .addComponent(PermanentApartmentNumber)
                                                .addComponent(PermanentCity)
                                                .addComponent(PermanentZipCode))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(fieldPermanentApartmentNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldPermanentCity, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldPermanentStreetName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(OfficePhone)
                                                .addComponent(OfficeEmail))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGap(156, 156, 156)
                                                    .addComponent(PermanentAddress))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(PersonalEmail)
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(PersonalPhone)))
                                                    .addGap(12, 12, 12)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(fieldPersonalPhone)
                                                        .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(NUID))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(LastName))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(FirstName))
                                        .addComponent(CollegeName))
                                    .addGap(65, 65, 65)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldNUID)
                                        .addComponent(fieldLastName)
                                        .addComponent(fieldCollegeName)
                                        .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContactInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OfficePhone)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PersonalPhone)
                        .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfficeEmail)
                    .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonalEmail)
                    .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentAddress)
                    .addComponent(PermanentAddress))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentStreetName)
                            .addComponent(fieldCurrentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrentApartmentNumber)
                            .addComponent(fieldCurrentApartmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrentCity)
                            .addComponent(fieldCurrentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrentZipCode)
                            .addComponent(fieldCurrentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PermanentStreetName)
                            .addComponent(fieldPermanentStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PermanentApartmentNumber)
                            .addComponent(fieldPermanentApartmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PermanentCity)
                            .addComponent(fieldPermanentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PermanentZipCode)
                            .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //logic to save the person details
        ContactInformation officeInfor = this.person.getOfficeInfor();
        ContactInformation personalInfor = this.person.getPersonalInfor();
        Address current_address = this.person.getCurrentAddress();
        Address permanent_address = this.person.getPermanentAddress();
        String reg = "^[0-9]+(.[0-9]+)?$";
        
        if (fieldNUID.getText().matches(reg)) {
            long NUID = Long.parseLong(fieldNUID.getText());
            this.person.setNUID(NUID);
        }else{
            JOptionPane.showMessageDialog(null, "NUID must be the number!");
        }
        String first_name = fieldFirstName.getText();
        String last_name = fieldLastName.getText();
        String college_name = fieldCollegeName.getText();
        if (fieldOfficePhone.getText().matches(reg)) {
            long office_phone = Long.parseLong(fieldOfficePhone.getText());
            officeInfor.setPhone(office_phone);
        }else{
            JOptionPane.showMessageDialog(null, "Office phone must be the number!");
        }
        String office_email = fieldOfficeEmail.getText();
        if (fieldPersonalPhone.getText().matches(reg)) {
            long personal_phone = Long.parseLong(fieldPersonalPhone.getText());
            personalInfor.setPhone(personal_phone);
        }else{
            JOptionPane.showMessageDialog(null, "Personal phone must be the number!");
        }
        String personal_email = fieldPersonalEmail.getText();
        String current_street_name = fieldCurrentStreetName.getText();
        if (fieldCurrentApartmentNumber.getText().matches(reg)) {
            int current_apartment_number = Integer.valueOf(fieldCurrentApartmentNumber.getText());
            current_address.setApartmentNumber(current_apartment_number);
        }else{
            JOptionPane.showMessageDialog(null, "Current apartment number must be the number!");
        }
        String current_city = fieldCurrentCity.getText();
        if (fieldCurrentZipCode.getText().matches(reg)) {
            int current_zipcode = Integer.valueOf(fieldCurrentZipCode.getText());
            current_address.setZipCode(current_zipcode);
        }else{
            JOptionPane.showMessageDialog(null, "Current zipcode must be the number!");
        }
        String permanent_street_name = fieldPermanentStreetName.getText();
        if (fieldPermanentApartmentNumber.getText().matches(reg)) {
            int permanent_apartment_number = Integer.valueOf(fieldPermanentApartmentNumber.getText());
            permanent_address.setApartmentNumber(permanent_apartment_number);
        }else{
            JOptionPane.showMessageDialog(null, "Permanent apartment number must be the number!");
        }
        String permanent_city = fieldPermanentCity.getText();
        if (fieldPermanentZipCode.getText().matches(reg)) {
            int permanent_zipcode = Integer.valueOf(fieldPermanentZipCode.getText());
            permanent_address.setZipCode(permanent_zipcode);
        }else{
            JOptionPane.showMessageDialog(null, "Permanent zipcode must be the number!");
        }
        
        this.person.setFirstName(first_name);
        this.person.setLastName(last_name);
        this.person.setCollegeName(college_name);
        officeInfor.setEmail(office_email);
        personalInfor.setEmail(personal_email);
        current_address.setStreetName(current_street_name);
        current_address.setCity(current_city);
        permanent_address.setStreetName(permanent_street_name);
        permanent_address.setCity(permanent_city);
        
        JOptionPane.showMessageDialog(null, "SAVED SUCCESSFULLY!");
        
        display();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCollegeNameActionPerformed

    private void fieldOfficePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfficePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfficePhoneActionPerformed

    private void fieldOfficeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfficeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfficeEmailActionPerformed

    private void fieldPersonalEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonalEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonalEmailActionPerformed

    private void fieldPersonalPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPersonalPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPersonalPhoneActionPerformed

    private void fieldCurrentStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentStreetNameActionPerformed

    private void fieldCurrentApartmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentApartmentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentApartmentNumberActionPerformed

    private void fieldCurrentCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentCityActionPerformed

    private void fieldCurrentZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurrentZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurrentZipCodeActionPerformed

    private void fieldPermanentStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentStreetNameActionPerformed

    private void fieldPermanentApartmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentApartmentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentApartmentNumberActionPerformed

    private void fieldPermanentCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentCityActionPerformed

    private void fieldPermanentZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentZipCodeActionPerformed

    private void viewOfficeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOfficeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOfficeEmailActionPerformed

    private void viewPermanentZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPermanentZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPermanentZipCodeActionPerformed

    private void viewPersonalEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonalEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPersonalEmailActionPerformed

    private void viewPersonalPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonalPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPersonalPhoneActionPerformed

    private void viewCurrentStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCurrentStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCurrentStreetNameActionPerformed

    private void viewCurrentApartmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCurrentApartmentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCurrentApartmentNumberActionPerformed

    private void viewCurrentCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCurrentCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCurrentCityActionPerformed

    private void viewCurrentZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCurrentZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCurrentZipCodeActionPerformed

    private void viewPermanentStreetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPermanentStreetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPermanentStreetNameActionPerformed

    private void viewCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCollegeNameActionPerformed

    private void viewLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewLastNameActionPerformed

    private void viewPermanentApartmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPermanentApartmentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPermanentApartmentNumberActionPerformed

    private void viewOfficePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOfficePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOfficePhoneActionPerformed

    private void viewPermanentCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPermanentCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewPermanentCityActionPerformed
    private void display(){
        viewNUID.setText(String.valueOf(this.person.getNUID()));
        viewFirstName.setText(this.person.getFirstName());
        viewLastName.setText(this.person.getLastName());
        viewCollegeName.setText(this.person.getCollegeName());
        viewOfficeEmail.setText(this.person.getOfficeInfor().getEmail());
        viewOfficePhone.setText(String.valueOf(this.person.getOfficeInfor().getPhone()));
        viewPersonalEmail.setText(this.person.getPersonalInfor().getEmail());
        viewPersonalPhone.setText(String.valueOf(this.person.getPersonalInfor().getPhone()));
        viewCurrentStreetName.setText(this.person.getCurrentAddress().getStreetName());
        viewCurrentApartmentNumber.setText(String.valueOf(this.person.getCurrentAddress().getApartmentNumber()));
        viewCurrentCity.setText(this.person.getCurrentAddress().getCity());
        viewCurrentZipCode.setText(String.valueOf(this.person.getCurrentAddress().getZipCode()));
        viewPermanentStreetName.setText(this.person.getPermanentAddress().getStreetName());
        viewPermanentApartmentNumber.setText(String.valueOf(this.person.getPermanentAddress().getApartmentNumber()));
        viewPermanentCity.setText(this.person.getPermanentAddress().getCity());
        viewPermanentZipCode.setText(String.valueOf(this.person.getPermanentAddress().getZipCode()));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CollegeName;
    private javax.swing.JLabel CollegeName1;
    private javax.swing.JLabel ContactInformation;
    private javax.swing.JLabel ContactInformation1;
    private javax.swing.JLabel CurrentAddress;
    private javax.swing.JLabel CurrentAddress1;
    private javax.swing.JLabel CurrentApartmentNumber;
    private javax.swing.JLabel CurrentApartmentNumber1;
    private javax.swing.JLabel CurrentCity;
    private javax.swing.JLabel CurrentCity1;
    private javax.swing.JLabel CurrentStreetName;
    private javax.swing.JLabel CurrentStreetName1;
    private javax.swing.JLabel CurrentZipCode;
    private javax.swing.JLabel CurrentZipCode1;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstName1;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JLabel NUID;
    private javax.swing.JLabel NUID1;
    private javax.swing.JLabel OfficeEmail;
    private javax.swing.JLabel OfficeEmail1;
    private javax.swing.JLabel OfficePhone;
    private javax.swing.JLabel OfficePhone1;
    private javax.swing.JLabel PermanentAddress;
    private javax.swing.JLabel PermanentAddress1;
    private javax.swing.JLabel PermanentApartmentNumber;
    private javax.swing.JLabel PermanentApartmentNumber1;
    private javax.swing.JLabel PermanentCity;
    private javax.swing.JLabel PermanentCity1;
    private javax.swing.JLabel PermanentStreetName;
    private javax.swing.JLabel PermanentStreetName1;
    private javax.swing.JLabel PermanentZipCode;
    private javax.swing.JLabel PermanentZipCode1;
    private javax.swing.JLabel PersonalEmail;
    private javax.swing.JLabel PersonalEmail1;
    private javax.swing.JLabel PersonalPhone;
    private javax.swing.JLabel PersonalPhone1;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldCurrentApartmentNumber;
    private javax.swing.JTextField fieldCurrentCity;
    private javax.swing.JTextField fieldCurrentStreetName;
    private javax.swing.JTextField fieldCurrentZipCode;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldOfficeEmail;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPermanentApartmentNumber;
    private javax.swing.JTextField fieldPermanentCity;
    private javax.swing.JTextField fieldPermanentStreetName;
    private javax.swing.JTextField fieldPermanentZipCode;
    private javax.swing.JTextField fieldPersonalEmail;
    private javax.swing.JTextField fieldPersonalPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField viewCollegeName;
    private javax.swing.JTextField viewCurrentApartmentNumber;
    private javax.swing.JTextField viewCurrentCity;
    private javax.swing.JTextField viewCurrentStreetName;
    private javax.swing.JTextField viewCurrentZipCode;
    private javax.swing.JTextField viewFirstName;
    private javax.swing.JTextField viewLastName;
    private javax.swing.JTextField viewNUID;
    private javax.swing.JTextField viewOfficeEmail;
    private javax.swing.JTextField viewOfficePhone;
    private javax.swing.JTextField viewPermanentApartmentNumber;
    private javax.swing.JTextField viewPermanentCity;
    private javax.swing.JTextField viewPermanentStreetName;
    private javax.swing.JTextField viewPermanentZipCode;
    private javax.swing.JTextField viewPersonalEmail;
    private javax.swing.JTextField viewPersonalPhone;
    // End of variables declaration//GEN-END:variables
}
