/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lucaszhang
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private DeliveryPackage delPackage; 
    private Product productViewed;
    
    public ViewJPanel() {
        initComponents();
    }
    
    ViewJPanel(DeliveryPackage delPackage) {
        initComponents();
        this.delPackage = delPackage;
        display();
        displayProductList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        packageId = new javax.swing.JTextField();
        packageWeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        customerName1 = new javax.swing.JTextField();
        customerId1 = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(51, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("package Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        packageId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageIdActionPerformed(evt);
            }
        });
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 103, -1));

        packageWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightActionPerformed(evt);
            }
        });
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, -1));

        jLabel2.setText("weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 20));

        jLabel3.setText("product id");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel4.setText("product name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel5.setText("customer name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel6.setText("customer Id");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel7.setText("price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 100, -1));

        productName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productName1ActionPerformed(evt);
            }
        });
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, -1));
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 100, -1));
        add(customerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 110, -1));
        add(customerId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, -1));

        btnShow.setText("SHOW");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });
        add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void packageIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageIdActionPerformed

    private void packageWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightActionPerformed

    private void productName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productName1ActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        productId1.setEnabled(false);
        
        int pid = (int)productComboBox.getSelectedItem();

        Product prod = this.delPackage.findProduct(pid);
        this.productViewed = prod;
         
        if (!prod.equals(null)) {
            productId1.setText(String.valueOf(pid));
            productName1.setText(prod.getProductName());
            productPrice1.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed
    
    public void display() {
        packageId.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWeight.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer customer = this.delPackage.getCustomer();
        customerId1.setText(String.valueOf(customer.getCustomerId()));
        customerName1.setText(customer.getFullName());
    }
    
    public void displayProductList() {
        for(Product p : this.delPackage.getProductList()) {
            productComboBox.addItem(p.getProductId());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShow;
    private javax.swing.JTextField customerId1;
    private javax.swing.JTextField customerName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWeight;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    // End of variables declaration//GEN-END:variables
}
