/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sUI;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDir;
import Customer.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import librarian.librarian;

/**
 *
 * @author lucaszhang
 */
public class LibrarianManagementJPanel extends javax.swing.JPanel {

    private Business business;
    private UserAccount useraccount;
    DefaultTableModel tableModel;
    /**
     * Creates new form LibrarianManagementJPanel
     */
    public LibrarianManagementJPanel() {
        initComponents();
    }
    
    
    LibrarianManagementJPanel(Business business, UserAccount useraccount) {
        initComponents();

        this.business = business;
        this.useraccount = useraccount;
        this.tableModel = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldusername1 = new javax.swing.JTextField();
        fieldname1 = new javax.swing.JTextField();
        fieldPassword1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 120, 30));
        add(fieldname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 30));
        add(fieldPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, 30));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

        UserAccountDir ua = this.business.getUad();

        if (ua.accountExists(fieldusername1.getText(), fieldPassword1.getText(), "librarian")) {
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        } else {
            // save the customer obj for user and useraccount credentials
            UserAccount user = this.business.getUad().createUserAccount(fieldusername1.getText(), fieldPassword1.getText(), "librarian");
            this.business.getLd().createlibrarian(user.getAccountId(), fieldname1.getText());
            populate();
        }
    }//GEN-LAST:event_addBtnActionPerformed
    
    public void populate() {

        tableModel.setRowCount(0);
        for (librarian l : this.business.getLd().getLd()) {
            UserAccount u = this.business.getUad().findById(l.getId());

            Object[] row = new Object[4];

            row[0] = l.getId();
            row[1] = l.getName();
            row[2] = u.getUsername();
            row[3] = u.getPassword();

            tableModel.addRow(row);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fieldPassword1;
    private javax.swing.JTextField fieldname1;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
