/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Restaurant.DeliveryAgent;
import Services.Order;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucaszhang
 */
public class OrderManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderManagementJPanel
     */
    private UserAccount useraccount;
    private Business business;
    DefaultTableModel tableModel;
    public OrderManagementJPanel() {
        initComponents();
    }

    OrderManagementJPanel(Business business, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        
        this.business=business;
        this.useraccount=useraccount;
        this.tableModel=(DefaultTableModel) jTable1.getModel();
        
        populateDp();
        
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignAgentBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignAgentBtn.setText("ASSIGN");
        assignAgentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignAgentBtnActionPerformed(evt);
            }
        });
        add(assignAgentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Customer", "Agent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignAgentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignAgentBtnActionPerformed
        // TODO add your handling code here:
        DeliveryAgent agent = (DeliveryAgent) jComboBox1.getSelectedItem();
        
        int selectedRow = jTable1.getSelectedRow();
        
        Order o = (Order) jTable1.getValueAt(selectedRow, 0);
        o.setAgent(agent);
        agent.addDeliveryOrder(o);
        
        populate();
    }//GEN-LAST:event_assignAgentBtnActionPerformed
    public void populate(){
            tableModel.setRowCount(0);
            for(Order o:this.business.getAllorders().getOrderlist()){
                
                Object[]row=new Object[3];
                
                row[0]=o;
                row[1]=o.getCustomer().getPersonID();
                row[2]=o.getAgent().getPersonID();
           
                
                tableModel.addRow(row);
                
            }
    }
    public void  populateDp(){
        jComboBox1.removeAllItems();
        for(DeliveryAgent d:this.business.getDeliveryAgentDirectory().getAgentList()){
            jComboBox1.addItem(d);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignAgentBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
